org: resourcingeducation
app: bibletags-data
component: express
name: bibletags-data-graphql

inputs:
  src: ./
  domain: ${param:domain}
  roleName: bibletags-data
  env:
    RDS_HOST: ${param:RDS_HOST}
    RDS_USERNAME: ${param:RDS_USERNAME}
    RDS_PASSWORD: ${param:RDS_PASSWORD}
    RDS_DATABASE: ${param:RDS_DATABASE}
    AUTH_SITE_ID: ${param:AUTH_SITE_ID}
    AUTH_DOMAIN: ${param:AUTH_DOMAIN}
    AUTH_JWT_SECRET: ${param:AUTH_JWT_SECRET}
    LOCAL: ''